name: Setup Environment
description: "Install runtime + dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
      shell: bash